apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-ingress
  namespace: default
spec:
  rules:
    - host: a74d7a55-b0d7-4b23-8a7e-282437802fe6.pub.instances.scw.cloud
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ template "helm.fullname" . }}-server
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "helm.fullname" . }}-client
                port:
                  number: 80
          - path: /login
            pathType: Exact
            backend:
              service:
                name: {{ template "helm.fullname" . }}-client
                port:
                  number: 80
