version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  api:
    container_name: recipe_api
    image: rg.nl-ams.scw.cloud/recipe/api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: [ "uvicorn", "app.main:app" ]
    env_file:
      - backend/.env
    depends_on:
      - db

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recipe_frontend
    image: rg.nl-ams.scw.cloud/recipe/vue-app
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
      - api

volumes:
  postgres-data:
