version: "3.7"

services:
  postgres:
    image: postgres:12.5
    env_file:
      - ".env"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  app:
    container_name: recipe_api
    build:
      context: .
    volumes:
      - ./:/app
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PYTHONUNBUFFERED
      - DEBUG
      - PORT
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgresql_data: